OneTimeNotes/urls.py
from django.conf.urls import url
from views import otnote, otnote_create, otn_stats

urlpatterns = [
    url(r'^otn$', otnote_create, name='otnote_create'),
    url(r'^otnote$', otnote_create, name='otnote_create'),
    url(r'^otn_stats$', otn_stats, name='otn_stats'),
    url(r'^n/(?P<note_id>[\da-zA-Z]{6})', otnote, name='otnote'),
]

OneTimeNotes/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models

class Notes(models.Model):
    encrypted_note = models.TextField(blank=True)
    token = models.CharField(max_length=6)
    timestamp = models.DateTimeField('Created on')

OneTimeNotes/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponse, HttpResponseBadRequest, Http404, HttpResponseNotAllowed
from django import forms
from OneTimeNotes.models import Notes
from string import ascii_letters, digits
from datetime import datetime
import random


# === VIEWS START HERE ===

# Definition of ignored User-Agents
ignoredUAs = [
 'WhatsApp',
 'TelegramBot',
 'Slackbot-LinkExpanding',
 'facebookexternalhit'
]


# OTN input handler
class OTNForm(forms.Form):
    private_note = forms.CharField(label='',widget=forms.Textarea(attrs={'cols': 50, 'rows': 15, 'placeholder': 'Input your note here'}))


# URL token generator
def generate_token(length):
    allowed_chars = ascii_letters + digits
    token = ''.join(random.sample(allowed_chars,length))
    return token

# delete entries older than 48 hours
def delete_old_notes():
    if not Notes.objects.count:
        return
    current = datetime.now()
    for note in Notes.objects.all():
        # tzinfo has to be removed for correct naive substraction
        difference = current - note.timestamp.replace(tzinfo=None)
        difference = int(difference.total_seconds())
        if difference > 48*60*60:
            note.delete()
    return


# handler for /n/<note_id> 
# <note-id> - 6 symbols [a-zA-Z0-9]
def otnote(request, note_id):
    if any(iua in request.META['HTTP_USER_AGENT'] for iua in ignoredUAs):
        raise Http404
    try:
        note = Notes.objects.get(token=note_id)
    except Notes.DoesNotExist:
        raise Http404
    otn = note.encrypted_note
    # delete the note from the DB
    note.delete()
    return render(request, 'decrypted_note.html', {'encrypted_note':otn})


# handler for /otnote
def otnote_create(request):
    delete_old_notes()
    if request.is_ajax():
        if request.method == 'GET':
            return HttpResponseBadRequest('This is XHR GET request... Are you a hacker? :P')
        elif request.method == 'POST':
            otn = request.POST['private_note']
            # discard messages bigger than 20Kb 
            if len(otn) > 20 * 1024:
                return HttpResponseBadRequest('Sorry, current note size limit: 20Kb')
            token = generate_token(6)
            already_exists = True
            while already_exists:
                try:
                    existing = Notes.objects.get(token=token)
                    token = generate_token(6)
                except Notes.DoesNotExist:
                    already_exists = False
            write_note = Notes.objects.create(encrypted_note=otn,token=token,timestamp=datetime.now())
            return HttpResponse(token)
        else:
            return HttpResponseNotAllowed(['POST only!'])
    else:
        form = OTNForm()
        return render(request,'otnote.html', {'form':form})


# handler for /otn_count
def otn_stats(request):
    delete_old_notes()
    count = Notes.objects.count()
    return HttpResponse(count)

OneTimeNotes/templates/decrypted_note.html
<!DOCTYPE HTML>
<html>

<head>
  <title>OneTimeNotes</title>
  <meta name="description" content="OneTimeNotes" />
  <meta name="keywords" content="onetimenotes, otn, one-time notes, antukh" />
  <meta http-equiv="content-type" content="text/html; charset=windows-1252" />
  <link rel="stylesheet" type="text/css" href="style/style.css" />
  <link rel="stylesheet" href="bootstrap/css/bootstrap.min.css">
  {% load static %}
  <script src={% static "js/jquery.min.js" %}></script>
  <script src={% static "bootstrap/js/bootstrap.min.js" %}></script>
  <script src={% static "js/triplesec-3.0.14-min.js" %}></script>
  <script src={% static "js/pack.js" %}></script>
  <script type="text/javascript">window.onload = Magic;</script>
</head>

<body>
  <div id="main">
    <div class="form-group" id="site_content">
        <form id="note">
          <h1>Your one-time note:</h1>
          <div class="form_settings">
            <tr><th></th><td><textarea cols="50" id="id_private_note" name="private_note" rows="15">{{ encrypted_note }}</textarea></td></tr>
            <div id="key_input" style="display:none">
                <br>
                <h2>Input your key to decrypt the note</h2>
                <input type="text" class="form_control" placeholder="secret_key" id='symmkey'><br>
            </div>
            <br>
            <span>&nbsp;</span>
            <button class="btn btn-secondary btn-lg submit_otn btn-decrypt" type="button" id="otn_decrypt" style="display:none" >Decrypt me!</button>
            <span>&nbsp;</span>
            </div>
        </form>
       </div>
  </div>
  <div class="footer">HQIBPEXEZMUG</div>
</body>
</html>

OneTimeNotes/templates/otnote.html
<!DOCTYPE HTML>
<html>

<head>
  <title>OneTimeNotes</title>
  <meta name="description" content="OneTimeNotes" />
  <meta name="keywords" content="onetimenotes, otn, one-time notes, antukh" />
  <meta http-equiv="content-type" content="text/html; charset=windows-1252" />
  <link rel="stylesheet" type="text/css" href="style/style.css" />
  <link rel="stylesheet" href="bootstrap/css/bootstrap.min.css">
  {% load static %}
  <script src={% static "js/jquery.min.js" %}></script>
  <script src={% static "bootstrap/js/bootstrap.min.js" %}></script>
  <script src={% static "js/triplesec-3.0.14-min.js" %}></script>
  <script src={% static "js/pack.js" %}></script>
</head>

<body>
  <div id="main">
    <div class="form-group" id="site_content">
        <form id="generate">
        <h1>Type your one-time note:</h1>
          <div class="form_settings">
            {% csrf_token %}
            {{ form }}
            <input type="hidden" class="form_control" value="secret" id='symmkey'><br>
            <p style="padding-top: 25px">
            <span>&nbsp;</span>
            <button class="btn btn-secondary btn-lg submit_otn btn-encrypt" type="button" onclick="setKey()" disabled=true>Encrypt & send</button>
            <span>&nbsp;</span>
            </div>
        </form>
        <form id="output" style="display:none">
           <h1>Your secret URL:</h1>
              <div class="alert alert-success priv_url" role="alert" id="priv_url_id">
                 Private URL will appear here shortly...
              </div>
        </form>
     </div>
  </div>
  <div class="footer">HQIBPEXEZMUG</div>
</body>

</html>